name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint, test, and build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install deps and build (with cache)
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
          run_install: |
            args: [--frozen-lockfile]

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Integration test
        run: pnpm test --coverage

      - name: Browser test
        run: pnpm test:browser:ci

      - name: Build
        run: pnpm build
